#!/usr/bin/env python
# -*- coding: utf-8 -*-
import budget, sys
from decimal import Decimal as D
MAX = D("31844.30")

b = budget.load_budget( "./" )

t = b.total()

if t > MAX:
    print >> sys.stderr, "Fail: Budget is £%s too high" % (t - MAX)
    exit (1)

print "OK:",
if t == MAX:
    print "Budget is at maximum."
else:
    print "Budget is £%s below maximum." % (MAX-t)

exit(0)


